service: slack-presence-proxy

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  stage: dev

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  getPresence:
    handler: bin/handler
    events:
      - http:
          path: getPresence
          method: get
